import Head from "next/head";

import MainHero from "@/components/modules/MainHero/Index";
import { heroData } from "@/data/Index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dylan Cramer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainHero data={...heroData} />
      </main>
    </>
  );
}
